apiVersion: v1
kind: Namespace
metadata:
  name: dev-environments
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"name":"dev-environments"}}