replicaCount: 1
namespace: dev-environments

image:
  ubuntu:
    repository: khana88/swish-final-project-ubuntu
    tag: "latest"
  alpine:
    repository: khana88/swish-final-project-alpine
    tag: "latest"

baseImage: ubuntu  # Choose between 'ubuntu' or 'alpine'

packages:
  ubuntu:
    - python3
    - nodejs
    - npm
  alpine:
    - curl
    - git

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

hpa:
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization: 50

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  name: ssh-service
  type: LoadBalancer
  port: 8080

ingress:
  enabled: true
  name: app-ingress
  className: "nginx"
  annotations: {}
  hosts:
    - host: alpine.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: ubuntu.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


resources:
  requests:
    memory: "2Gi"
    cpu: "500m"
  limits:
    memory: "4Gi"
    cpu: "1"

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

ssh:
  privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    ... (your private key here) ...
    -----END RSA PRIVATE KEY-----

