apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dev-environment.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  packages: |
    {{- range $index, $element := index .Values.packages .Values.baseImage }}
    {{ $element }}
    {{- end }}
