apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dev-environment.fullname" . }}-ssh
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  privateKey: {{ .Values.ssh.privateKey | b64enc }}
