apiVersion: v1
kind: Service
metadata:
  name: {{ include "dev-environment.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "dev-environment.name" . }}
  ports:
    - protocol: TCP
      port: 8080  # External port exposed by the service
      targetPort: 8080  # Internal port on which the container listens
  type: {{ .Values.service.type }}
