apiVersion: apps/v1
kind: Deployment
metadata:
  name: swish-nodejs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swish-app
  template:
    metadata:
      labels:
        app: swish-app
    spec:
      containers:
        - name: nodejs-app
          image: swish-nodejs-app:latest  # Replace with your Docker image
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swish-python-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: swish-python-app:latest  # Replace with your Docker image
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "0.5"
              memory: "256Mi"
            requests:
              cpu: "0.25"
              memory: "128Mi"
