apiVersion: v1
kind: Pod
metadata:
  name: node-affinity
spec:
  containers:
    - name: nodejs-app
      image: nodejs-image:${BUILD_NUMBER}
      # Other container specs
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-type
                operator: In
                values:
                  - backend

---
apiVersion: v1
kind: Pod
metadata:
  name: node-affinity
spec:
  containers:
    - name: python-app
      image: python-image:${BUILD_NUMBER}
      # Other container specs
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-type
                operator: In
                values:
                  - frontend
