apiVersion: v1
kind: Service
metadata:
  name: your-app-service
spec:
  selector:
    app: your-app  # Selector to match Pods
  ports:
    - protocol: TCP
      port: 80  # Port exposed externally (adjust as needed)
      targetPort: 3000  # Port on Pods (must match containerPort in deployment.yaml)
  type: LoadBalancer  # Type of service (LoadBalancer, NodePort, ClusterIP, etc.)
