apiVersion: v1
kind: Service
metadata:
  name: ssh-service-ubuntu
  namespace: dev-environments
spec:
  selector:
    app: ubuntu-app
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  type: LoadBalancer  # Use NodePort if LoadBalancer is not available
